apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecow-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # TLS IS ENABLED USING A SELF-SIGNED CERTIFICATE STORED IN THE 'WISECOW-TLS' SECRET
spec:
  tls:
    - hosts:
        - wisecow.local
      secretName: wisecow-tls  # SELF-SIGNED CERT CREATED USING:
      # OPENSSL REQ -X509 -NODES -DAYS 365 -NEWKEY RSA:2048 -KEYOUT TLS.KEY -OUT TLS.CRT -SUBJ "/CN=WISECOW.LOCAL/O=WISECOW"
      # KUBECTL CREATE SECRET TLS WISECOW-TLS --KEY TLS.KEY --CERT TLS.CRT
  rules:
    - host: wisecow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wisecow-service
                port:
                  number: 80
