apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy

metadata:
  name: wisecow-zero-trust
  namespace: default

spec:
  selector:
    matchLabels:
      app: wisecow-deployment
  file:
    matchPaths:
      - path: /app
        action: Block
  process:
    matchPaths:
      - path: /bin/bash
        action: Block
  action: Block
  severity: 1

