name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 #GETS REPO FILES INSIDE WORKFLOW RUNNER.

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} #SCRRETS ARE STORED IN REPO SECRETS

    - name: Build Docker image
      run: |
        docker build -t vishnu5031/vishnu2003cl:latest .

    - name: Push Docker image
      run: |
        docker push vishnu5031/vishnu2003cl:latest
      #ON SUCCESSFULL BUILD UPLOADING THE BUILT IMAGE TO DOCKER REGISTRY 
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/wisecow-deployment wisecow=vishnu5031/wishecow:latest 
        kubectl rollout status deployment/wisecow-deployment
